import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

// Content lives at the repo root (fragments/, posts/, journeys/, identities/),
// not inside site/ — see SPEC.md section 2. The glob loader reads it in place
// so the archive stays a plain directory of markdown, independent of the site.
// `base` is resolved relative to the Astro project root (site/), one level
// up from here, not relative to this config file.
const repoRoot = '../';

const fragments = defineCollection({
  loader: glob({ pattern: '**/*.md', base: `${repoRoot}fragments` }),
  schema: z.object({
    id: z.string(),
    captured_at: z.coerce.date(),
    // markdown: a fragment whose body IS the content — a document worth
    // dropping into a post as its own object (a process doc, a spec) rather
    // than folded into the post's own prose. Rendered as real markdown
    // (headings, lists, bold, code), collapsed behind a click — see
    // components/Fragment.astro and lib/markdown.ts.
    type: z.enum(['photo', 'text', 'video', 'audio', 'markdown']),
    // Omitted for text fragments. Each entry is EITHER an R2 object key (photos,
    // e.g. "f/2026-08-18/192314-1.webp") OR a repo-relative local path (video/
    // audio, e.g. "media/video/2026-08-28-192734.mp4"). The renderer tells them
    // apart by the "media/" prefix — see lib/local-media.ts. Video/audio are
    // committed to the repo, not uploaded to R2 (see scripts/ingest.py).
    media: z.array(z.string()).optional(),
    // Cinematic color grading (the internal inbox's preset buttons) NEVER
    // touches an entry in media[] above — that stays the original, forever.
    // Grading instead maintains a separate derived copy per photo and keeps
    // this map pointing at whichever one is current; a key here is the
    // STRING index into media[] (YAML/JSON object keys are always strings)
    // whose original that graded copy was made from. An index absent from
    // this map means that photo has never been graded — render media[] as
    // usual. "Revert to original" is simply removing that photo's entry
    // here; the graded R2 copy itself gets a new key every time a preset is
    // (re-)applied, specifically so old copies never linger at a URL a
    // browser or CDN might have cached — see scripts/apply_cinematic_grade.py.
    graded: z.record(z.string()).optional(),
    journey: z.string().nullable(),
    spark: z.boolean(),
    consumed_by: z.string().nullable(),
    source: z.literal('telegram'),
  }),
});

const posts = defineCollection({
  loader: glob({ pattern: '*.md', base: `${repoRoot}posts` }),
  schema: z.object({
    slug: z.string(),
    title: z.string(),
    published: z.coerce.date(),
    journey: z.string().nullable(),
    // ordered; controls render order
    fragments: z.array(z.string()),
    // IMPLEMENTATION-SPEC.md stage 1: new optional fields, defaults only.
    // status: in_progress posts render with an honest "in progress" mark.
    status: z.enum(['in_progress', 'published']).optional().default('published'),
    // kind: insight posts are realizations returned to on /coordinates.
    kind: z.enum(['post', 'insight']).optional().default('post'),
    // Optional raw transcript: a filename in the repo-root transcripts/ dir.
    // When present it renders at the very bottom of the post, collapsed, as the
    // "before cleanup" record. Absent → nothing renders.
    transcript: z.string().optional(),
    // Optional narration: an R2 key (or local media/ path) to an audio file
    // that reads the post aloud. When present, a "Listen" player renders at the
    // top. Generated by scripts/generate_post_audio.py. Absent → nothing.
    audio: z.string().optional(),
  }),
});

const journeys = defineCollection({
  loader: glob({ pattern: '*.md', base: `${repoRoot}journeys` }),
  schema: z
    .object({
      slug: z.string(),
      title: z.string(),
      identity: z.string(),
      status: z.enum(['active', 'paused', 'abandoned', 'completed']),
      // IMPLEMENTATION-SPEC.md stage 1: how a journey behaves, drives the
      // hero proportions + the three Obsession streams (default create).
      path: z.enum(['practice', 'learn', 'create']).optional().default('create'),
      started: z.coerce.date(),
      ended: z.coerce.date().optional(),
      emerged_from: z.string().nullable(),
      reason: z.string().optional(),
    })
    .superRefine((journey, ctx) => {
      // SPEC.md 3.3: reason is REQUIRED when status is abandoned. Build fails without it.
      if (journey.status === 'abandoned' && !journey.reason) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['reason'],
          message: `journey "${journey.slug}" is abandoned but has no "reason". reason is required for abandoned journeys.`,
        });
      }
      // SPEC.md 3.3: ended is required if abandoned or completed.
      if ((journey.status === 'abandoned' || journey.status === 'completed') && !journey.ended) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['ended'],
          message: `journey "${journey.slug}" has status "${journey.status}" but no "ended" date. ended is required for abandoned or completed journeys.`,
        });
      }
    }),
});

const identities = defineCollection({
  loader: glob({ pattern: '*.md', base: `${repoRoot}identities` }),
  schema: z.object({
    slug: z.string(),
    title: z.string(),
    order: z.number(),
  }),
});

// IMPLEMENTATION-SPEC stage 4: /about is a dated, append-only stack. Each file
// in about/ is one entry, newest on top; older entries recede through ink →
// graphite → ghost. `mix` is the obsessions that sized that period of life —
// each carries its OWN explicit weight, so the size/colour is driven by a real
// signal per entry, not by list order. Every weight resolves to an explicit
// size+colour pair in about.astro; there is no index-based fallback.
const about = defineCollection({
  loader: glob({ pattern: '*.md', base: `${repoRoot}about` }),
  schema: z.object({
    date: z.coerce.date(),
    season: z.string(),
    // A short, dry, self-observed aside in the Caveat margin voice — the M2
    // mock's "sound came back this month. of course it did." Optional: an
    // entry without one renders no extra line.
    aside: z.string().optional(),
    mix: z
      .array(
        z.object({
          slug: z.string(),
          weight: z.enum(['dominant', 'present', 'emerging', 'quiet']),
        })
      )
      .optional(),
  }),
});

// Marginalia: photographed index-card-sized lines — original or collected,
// self-authored or attributed. Posted directly from Telegram (caption tagged
// `#marginalia`) straight to a live page, not curated through fragments/posts
// like everything else. Photo only, no OCR — the card itself is the record.
const marginalia = defineCollection({
  loader: glob({ pattern: '*.md', base: `${repoRoot}marginalia` }),
  schema: z.object({
    id: z.string(),
    captured_at: z.coerce.date(),
    // R2 object key (e.g. "m/2026-09-01/143022.webp") or a repo-relative
    // media/ path — same convention as fragment media, see lib/local-media.ts.
    media: z.string(),
    // Attribution when collected (author/book/film); absent when original.
    source: z.string().nullable().optional(),
  }),
});

export const collections = { fragments, posts, journeys, identities, about, marginalia };
